project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: "files/no_bee.png"
  google-analytics: "G-YZBNVRR4EQ"
  page-footer:
    center: |
      *a Tea Swamp project* 
      <br>
      <img src="https://raw.githubusercontent.com/teaswamp-creations/galiwatch.ca/quarto-website/images/teaswamp_transparent.png" alt="logo" class="image" style="width: 2.5em;">
  navbar:
    logo: "files/no_bee.png"
    left:
      - href: index.qmd
        text: Home
      - href: gallery.qmd
        text: Bees! 
    right:
      - text: "More"
        menu:
          - href: https://www.galiwatch.ca/index.html
            text: Operation Galiwatch
          - stats.qmd
          - references.qmd 
      
format:
  html:
    theme: [yeti, css/light-theme.scss]
    css: [css/styles.css, https://use.fontawesome.com/releases/v6.0.0/css/all.css]
    include-after_body: footer.html
    toc: true



