project:
  type: website
  output-dir: docs

website:
  title: "Bee Book Demo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - gallery.qmd
    right:
      - href: https://www.galiwatch.ca/index.html
        text: Operation Galiwatch
        icon: box-arrow-up-right

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



