# Andrena

**Kingdom: Animalia; Phylum: Arthropoda; Class Hymenoptera; Superfamily: Apoidea; Family: Andrenidae**

52 species listed by Shefield and Heron (2018) including 11 with verified iNaturalist records plus one additional iNaturalist record of Andrena astragali (death camas mining bee) that was first documented in the Pacific Maritime in 2018.

### Summary {.unnumbered}

The Pacific Maritime has 53 documented species of Andrena.

* 12 species with verified iNaturalist sightings (2018-2023) (A. amphibola, A. astragali, A. auricoma, A. columbiana, A. crataegi, A. frigida, A. milwaukeensis, A. miserabilis, A. nigrocaerulea, A. prunorum, A. transnigra, and A. vicina) 
* 12 species with verified iNaturalist sightings in other locations in North America (A. angustitarsata, A. barbilabris, A. caerulea, A. erythrogaster, A. forbesii, A. hippotes, A. melanchroa, A. miranda, A. nigrihirta, A. nivalis, A. rufosignata, and A. thaspii) 
* 18 species from the UBC Spencer collection (A. buckelli, A. candida, A. chlorura, A. cressonii infasciata, A. cupreotincta, A. cyanophila, A. hemileuca, A. medionitens, A. perarmata, A. saccate, A. saliciloris, A. scurra, A. stratifrons, A. subtilis, a. trevoris, A. vicinoides and w-scripta) 
* 11 species with no record in the UBC Spencer collection or iNaturalist (A. excellens, A. fulvicrista, A. lillooentensis, A. mariae, A. perplexa, A. schuhi, A. sigmundi, A. singularis, A. subaustralis, A. vierecki, and A. washingtoni).




